### ISSUE TITLE
Resend email confirmation not working on an Organization (Tenant) 

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim-barcelona#150]
#### :tophat: User Story

We don't know if this is for all decidim or only on this Organization (Tenant). 

On https://meta.decidim.barcelona/, when I create a non confirmed user and I try to login I get the message that I need to confirm the email, but when I go to resend confirmation instructions the system says that I'm already confirmed. 

![image](https://user-images.githubusercontent.com/717367/30692188-b6f7fb1c-9eca-11e7-9d92-cbca0e82f3f9.png)

![image](https://user-images.githubusercontent.com/717367/30692191-b8dd61ec-9eca-11e7-923e-6fc04fb18d71.png)

**Comment by josanFFiG** [comment]
As I've talked with @josepjaume here there are more screenshots from error messages new users are reciving...

1. When following the link given on the invitation's e-mail to become "Collaborator":

![captura de 2017-10-17 11-55-10](https://user-images.githubusercontent.com/27766903/31661583-8ba56e92-b33b-11e7-858b-c18e789c7b69.png)

2. When following the link given on the invitation's e-mail to become "Administrator":

<img width="1421" alt="screen shot 2017-10-10 at 17 15 02" src="https://user-images.githubusercontent.com/27766903/31661728-08033afa-b33c-11e7-8c5c-84b0eeafbfcd.png">

@mrcasals I hope these can be usefull for you to solve the bug.

**Comment by mrcasals** [comment]
I think this was solved in https://github.com/decidim/decidim/pull/2020, will be live in version 0.7.0.

**Comment by josanFFiG** [comment]
@mrcasals We have detected a new casuistry based on this error.
One of our mates on Decidim Team with mail @bcn.cat followed the steps to register in https://meta.decidim.barcelona/ without problem but she doesn't receive the confirmation email of this registry.
We have alredy checked on spam folder -just in case- to be sure about that, and there's no mail neither.

**Comment by josepjaume** [comment]
@josanFFiG we've also seen this in the past - it looks like bcn's mail services are blocking mail coming from hosts other than theirs. That's something that should be done from their side!

**Comment by josanFFiG** [comment]
OKI DOKI @josepjaume! 
We are notifying this to the mail service providers... let's see.

**Comment by josanFFiG** [comment]
After new or last release, we still having this problem to solve:

![photo_2017-10-22_13-11-22](https://user-images.githubusercontent.com/27766903/32006305-c4d9e24e-b9a6-11e7-94e9-99531bda87e7.jpg)

This screenshot was captured last sunday october 22nd.
